# Generated by Django 2.2.5 on 2020-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Decorative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=2000)),
                ('budget', models.IntegerField()),
                ('lux', models.IntegerField()),
            ],
        ),
    ]
