# Generated by Django 2.2.5 on 2020-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0004_auto_20200110_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='care',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='_care_companies_+', to='makeup.FavCare'),
        ),
    ]
